In [0]:
import numpy as np

In [7]:
a = np.array([1,2,0,3,-1])

b = np.array([[1,3,2,-2,-2],
              [2,1,2,-1,-2],
              [1,2,1,-2,-1],
              [1,2,2,-1,-1]])

print(a.shape)
display(a)
print(b.shape)
display(b)

c = b - a
display(c)

display(c**2)
display(c.sum())

(5,)


array([ 1,  2,  0,  3, -1])

(4, 5)


array([[ 1,  3,  2, -2, -2],
       [ 2,  1,  2, -1, -2],
       [ 1,  2,  1, -2, -1],
       [ 1,  2,  2, -1, -1]])

array([[ 0,  1,  2, -5, -1],
       [ 1, -1,  2, -4, -1],
       [ 0,  0,  1, -5,  0],
       [ 0,  0,  2, -4,  0]])

array([[ 0,  1,  4, 25,  1],
       [ 1,  1,  4, 16,  1],
       [ 0,  0,  1, 25,  0],
       [ 0,  0,  4, 16,  0]])

-12

In [4]:
c = np.zeros((4,5))
for k in range(c.shape[0]):
    c[k,:] = b[k,:] + a

display(c)

array([[ 2.,  5.,  2.,  1., -3.],
       [ 3.,  3.,  2.,  2., -3.],
       [ 2.,  4.,  1.,  1., -2.],
       [ 2.,  4.,  2.,  2., -2.]])

In [21]:
display(b.shape)
display(a.shape)
d = np.dot(b[:,:],a[:,np.newaxis])
display(d.sum())
display(d.shape)
e = np.sum(d ** 2)
display(e)

f = b[:,:] - a[np.newaxis,:]
display(f)

(4, 5)

(5,)

9

(4, 1)

27

array([[ 0,  1,  2, -5, -1],
       [ 1, -1,  2, -4, -1],
       [ 0,  0,  1, -5,  0],
       [ 0,  0,  2, -4,  0]])

In [10]:
display(a)
display(a.sum())

array([ 1,  2,  0,  3, -1])

5

In [16]:
a = np.array([1,2,0,3,-1])

b = np.array([[1,3,2,-2,-2],
              [2,1,2,-1,-2],
              [1,2,1,-2,-1],
              [1,2,2,-1,-1]])
c = np.array([[1,3,2,-2,-2],
              [2,1,2,-1,-2],
              [1,2,1,-2,-1],
              [1,2,2,-1,-1]])
display(b.shape)
d = np.dot(b,c.T)

display(d.shape)
display(d)

d = np.diag(d)
display(d.shape)
display(d)


(4, 5)

(4, 4)

array([[22, 15, 15, 15],
       [15, 14, 10, 11],
       [15, 10, 11, 10],
       [15, 11, 10, 11]])

(4,)

array([22, 14, 11, 11])

p_1 = 1/(1+T.exp(-T.dot(X,w)))
  xent = -y * T.log(p_1) - (1-y)*T.log(1-p_1)
  